<a href="https://colab.research.google.com/github/robin0314/LA/blob/main/%5B00%5D%EC%8B%A4%EC%8A%B5_ZERO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import numpy as np

In [3]:
def print_val(x):
  print("Type:", type(x))
  print("Shape:", x.shape)
  print("값: \n", x)
  print(" ")

In [5]:
x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값: 
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값: 
 [5 2 3]
 


In [6]:
y = np.array([[1,2,3], [4,5,6]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값: 
 [[1 2 3]
 [4 5 6]]
 


In [7]:
a = np.zeros((2,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값: 
 [[0. 0.]
 [0. 0.]]
 


In [8]:
a = np.ones((3,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


In [10]:
a = np.eye(3,3)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


In [11]:
a = np.random.random((4,4))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값: 
 [[0.36315776 0.6995458  0.36186631 0.86147029]
 [0.03976678 0.04437418 0.11433791 0.82134556]
 [0.11611838 0.25025201 0.53766856 0.76556422]
 [0.98207573 0.9155754  0.96402785 0.19059385]]
 


In [13]:
a = np.random.randn(4,4)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값: 
 [[ 0.02231427  1.88001212 -0.96713191 -0.45568399]
 [ 0.03803433 -1.50876771 -1.00674855  0.14031639]
 [-0.67865531  0.11022911 -0.84507002  0.73622623]
 [-1.73832111  0.9458875   0.24253726 -0.44566145]]
 
